name: Build and Release

on:
  push:
    branches:
      - main  # 或者你使用的分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17  # 替换为你项目所需的 JDK 版本

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Pre-Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-latest
          release_name: Latest Pre-Release
          prerelease: true
          files: build/libs/Minecraft.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
