name: Gradle Build

on:
  push:
    branches: [ "**" ]  # 所有分支提交都会触发
  pull_request:
    branches: [ "**" ]  # PR 也触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 18

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace
